package com.factsmachine.service.error

class FactNotFoundException: RuntimeException("There is no fact with such id")